const String AUTO_APPOINTMENT_SCHEDULING_COLLECTION = 'autoAppointmentsScheduling';

const String AUTO_APPOINTMENT_SCHEDULING_FIELD_ID = "id";
const String AUTO_APPOINTMENT_SCHEDULING_FIELD_SHIFT_ID = "shiftId";
const String AUTO_APPOINTMENT_SCHEDULING_FIELD_DENTIST_ID = "dentistId";
const String AUTO_APPOINTMENT_SCHEDULING_FIELD_AGREEMENT_ID = "agreementId";
const String AUTO_APPOINTMENT_SCHEDULING_FIELD_PROCEDURE_ID = "procedureId";
const String AUTO_APPOINTMENT_SCHEDULING_FIELD_PATIENT = "patient";
const String AUTO_APPOINTMENT_SCHEDULING_FIELD_EMAIL  = "email";
const String AUTO_APPOINTMENT_SCHEDULING_FIELD_TELEPHONE = "telephone";
const String AUTO_APPOINTMENT_SCHEDULING_FIELD_DATE_APPOINTMENT_SCHEDULING = "dateAppointmentScheduling";
const String AUTO_APPOINTMENT_SCHEDULING_FIELD_PATIENT_ACCOUNT_ID = "patientAccountId";