name: ClinicaBambi
description: The web site of the 'Clinica Bambi'
version: 0.0.1
#homepage: https://www.example.com
#author: Edrick Alves <email@example.com>

environment:
  sdk: '>=2.0.0-dev.61.0 <3.0.0'

dependencies:
  angular: ^5.0.0-alpha+13
  angular_forms: ^2.0.0-alpha+5
  angular_router: ^2.0.0-alpha
  angular_components: ^0.9.0-alpha
  async: ^2.0.6
  build: '>=0.11.1 <0.13.0'
  js: ^0.6.1
  sass_builder: ^2.0.0
  build_config: '>=0.2.6 <0.4.0'
  firebase: ^5.0.0
  intl: ^0.15.7
  service_worker: ^0.2.3
  google_maps: ">=3.0.0 <4.0.0"
  crypto: ^2.0.6


dev_dependencies:
  build_runner: ^0.10.1
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0


transformers:
- angular:
    entry_points:
      - web/main.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
