name: ClinicaBambi
description: The web site of the 'Clinica Bambi'
version: 0.0.1
#homepage: https://www.example.com
#author: Edrick Alves <email@example.com>

environment:
  sdk: '>=2.1.1-dev.3.2 <3.0.0' #'>=2.0.0-dev.61.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_forms: ^2.1.4
  angular_router: ^2.0.0-alpha
  angular_components: ^0.14.0-alpha+1 
  async: ^2.0.6
  build: ^1.2.1
  js: ^0.6.1+1
  sass_builder: ^2.1.3
  build_config: ^0.4.1+1
  firebase: ^6.0.0
  intl: '>=0.13.0 <0.16.0'
  service_worker: ^0.2.3
  google_maps: ">=3.0.0 <4.0.0"
  analyzer: ^0.37.0

dev_dependencies:
  build_runner: ^1.7.2
  build_test: ^0.10.9+1
  build_web_compilers: ^2.7.1 

transformers:
- angular:
    entry_points:
      - web/main.dart
- dart_to_js_script_rewriter