name: ClinicaBambi
description: The web site of the 'Clinica Bambi'
version: 0.0.1
#homepage: https://www.example.com
#author: Edrick Alves <email@example.com>

environment:
  sdk: '>=2.1.1-dev.3.2 <3.0.0' #'>=2.0.0-dev.61.0 <3.0.0'

dependencies:
  angular: ^6.0.1 # ^5.0.0-alpha+13
  angular_forms: ^3.0.0
  angular_router: ^2.0.0-alpha
  angular_components: ^1.0.2
  async: ^2.0.6
  build: ^1.5.0 # '>=0.11.1 <0.13.0'
  js: ^0.6.1
  sass_builder: ^2.0.0
  build_config: ^0.4.3
  firebase: ^5.0.0
  intl: ^0.16.1
  service_worker: ^0.2.3
  google_maps: ">=3.0.0 <4.0.0"
  analyzer: '>=0.35.0 <0.41.0'
  time: ^1.2.0

dev_dependencies:
  build_runner: ^1.10.6
  build_test: ^0.10.9+1
  build_web_compilers: '>=2.12.0 <3.0.0'
  build_daemon: ^2.1.0

transformers:
- angular:
    entry_points:
      - web/main.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc