const String DENTIST_QUANTITY_PER_SHIFT_BY_DAY_OF_WEEK_COLLECTION = "dentistQuantityPerShiftByDayOfWeek";

const String DENTIST_QUANTITY_PER_SHIFT_BY_DAY_OF_WEEK_FIELD_ID = "id";
const String DENTIST_QUANTITY_PER_SHIFT_BY_DAY_OF_WEEK_FIELD_DAY_OF_WEEK = "dayOfWeek";
const String DENTIST_QUANTITY_PER_SHIFT_BY_DAY_OF_WEEK_FIELD_DENTIST_ID = "dentistId";
const String DENTIST_QUANTITY_PER_SHIFT_BY_DAY_OF_WEEK_FIELD_SHIFT_ID = "shiftId";
const String DENTIST_QUANTITY_PER_SHIFT_BY_DAY_OF_WEEK_FIELD_QUANTITY = "quantity";
