const String PERIOD_BY_SHIFT_BY_DAY_OF_WEEK_COLLECTION = "periodByShiftByDayOfWeek";

const String PERIOD_BY_SHIFT_BY_DAY_OF_WEEK_FIELD_ID = "id";
const String PERIOD_BY_SHIFT_BY_DAY_OF_WEEK_FIELD_SHIFT_ID = "shiftId";
const String PERIOD_BY_SHIFT_BY_DAY_OF_WEEK_FIELD_DAY_OF_WEEK = "dayOfWeek";
const String PERIOD_BY_SHIFT_BY_DAY_OF_WEEK_FIELD_DESCRIPTION = "description";
const String PERIOD_BY_SHIFT_BY_DAY_OF_WEEK_FIELD_STATE = "state";