final AGREEMENT_COLLECTION = "agreement";
final AGREEMENT_ID_FIELD = "id";
final AGREEMENT_DESCRIPTION_FIELD = "description";
final AGREEMENT_STATE_FIELD = "state";

final AGREEMENT_COLLECTION_MODEL = [
  {AGREEMENT_ID_FIELD: "String"},
  {AGREEMENT_DESCRIPTION_FIELD: "String"},
  {AGREEMENT_STATE_FIELD: "Boolean"}
];
