final REQUIREMENT_COLLECTION = 'requirement';
final REQUIREMENT_ID_FIELD = "id";
final REQUIREMENT_DESCRIPTION_FIELD = "description";
final REQUIREMENT_STATE_FIELD = "state";

final REQUIREMENT_COLLECTION_MODEL = [
  [REQUIREMENT_ID_FIELD, "String", "Id"],
  [REQUIREMENT_DESCRIPTION_FIELD, "String", "Convênio"],
  [REQUIREMENT_STATE_FIELD, "Boolean", "Estado"]
];