const String DENTIST_PROCEDURE_BY_DAY_OF_WEEK_BY_SHIFT_COLLECTION = 'dentistProcedureByDayOfWeekByShift';

const String DENTIST_PROCEDURE_BY_DAY_OF_WEEK_BY_SHIFT_FIELD_ID = "id";
const String DENTIST_PROCEDURE_BY_DAY_OF_WEEK_BY_SHIFT_FIELD_DENTIST_PROCEDURE_BY_DAY_OF_WEEK_ID =
    "dentistProcedureByDayOfWeekId";
const String DENTIST_PROCEDURE_BY_DAY_OF_WEEK_BY_SHIFT_FIELD_SHIFT_ID = "shiftId";
